### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [miZyind/loopnexts#2]
Hi,
I'm a Logo/Icon designer... Saw your very nice project and I'm really interested in giving my Free contribution to your awesome project by creating a Logo/Icon for your project, as my love and passion to always help contribute to awesome Open Source projects... 

Currently working on some ideas concept at the moment, I will share them with you here, so you can give your feedback on the design and or suggest any possible change or tweaks you might want to suit your project needs.

Would appreciate your response...
Regards!

**Comment by miZyind** [comment]
Wau! That would be pretty pretty cool if there is a unique logo for this project! Thanks for your attention to this small project 😄. Feel free to share and contribute your great creation!

Some suggestions:
 - It'd be awesome if the logo can include the design elements from `LoopBack`, `NextJS`, `TypeScript`, and `SemanticUI`. Because they are the main frameworks that this project inherited from.
- TypeScript is my favorite programming language! I also like the city perspective image and the colors on [its landing page](https://www.typescriptlang.org/) very much!

Thanks!

**Comment by chimzycash** [comment]
I appreciate your response... Would get the idea concept ready for your feedback

**Comment by chimzycash** [comment]
Hi... here is my logo idea concept... You can give your feedback and also suggest any logo color of your choice.
For the Logo, I drew inspiration from all the languages used to create a unique identity.

![LOGO DESIGN_LoopNexts_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/61323042-ed899e00-a806-11e9-8d89-6c2521fb1cf9.jpg)
![LOGO DESIGN_LoopNexts_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/61323043-ed899e00-a806-11e9-8cd2-963177f98434.jpg)
![LOGO DESIGN_LoopNexts_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/61323044-ee223480-a806-11e9-9d6f-3a61e5198eca.jpg)
![LOGO DESIGN_LoopNexts_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/61323045-ee223480-a806-11e9-9972-ad3ac457b01a.jpg)
![LOGO DESIGN_LoopNexts_idea concept_NEW](https://user-images.githubusercontent.com/37814297/61323046-eebacb00-a806-11e9-836d-7f62d49cde96.jpg)

**Comment by miZyind** [comment]
It looks awesome! I pretty like it!
Could you create a pull request so that I can merge your great contribution into this project?
I appreciate you for the work you have done 😄

**Comment by chimzycash** [comment]
Glad that you like the design... will prepare the files and create a PR

**Comment by chimzycash** [comment]
Hi... Created a Pull Request containing the logo files...

**Comment by miZyind** [comment]
I've accepted and merged your pull request! Thanks for your awesome work!
